#!/bin/zsh

# lichtgehen kompilieren und ausführen

rm ./lichtgehen

#export CXXFLAGS="-Wall -Werror -Wno-parentheses -std=c++14 -O3"
export CXXFLAGS="-Wall -Werror -Wno-parentheses -std=c++14 -O0 -ggdb"

echo "Kompiliere lichtgehen…"
make -j1 || exit

echo "Starte lichtgehen…"
#<../Spielraster/simple.txt ./lichtgehen

#BOTB="../src/lichtgehen"
BOTA="bots/dummybot/bot"

#BOTB="../src/lichtgehen"
#BOTB="bots/Burow/FalkBot"
#BOTB="bots/Wagenfuehr/bot"
BOTB="../javatron.jar"

SPIELRASTER="Test.txt"
#SPIELRASTER="../Spielraster/Test.txt"
#SPIELRASTER="../Spielraster/simple.txt"
#SPIELRASTER="../Spielraster/200x200.txt"
#SPIELRASTER="../Spielraster/100x100.txt"
#SPIELRASTER="../Spielraster/50x50.txt"
#SPIELRASTER="../Spielraster/5x5.txt"
#SPIELRASTER="../Spielraster/10x10.txt"
SPIELRASTER="../Spielraster/Säulen_21.txt"
#SPIELRASTER="../Spielraster/Säulen_Test.txt"
#SPIELRASTER="../Spielraster/Ring.txt"
#SPIELRASTER="../Spielraster/Ring_Test.txt"
#SPIELRASTER="../Spielraster/Ring4.txt"
#SPIELRASTER="../Spielraster/Labyrinth.txt"
#SPIELRASTER="../Spielraster/Raumfüllen_1.txt"
#SPIELRASTER="../Spielraster/Raumfüllen_2.txt"
#SPIELRASTER="../Spielraster/Raumfüllen_3.txt"
#SPIELRASTER="../Spielraster/Räume.txt"

# nur ein Bot
#SPIELRASTER="../Spielraster/5x5_1.txt"

# Eigenes Spiel
  #echo "Eigenes Spiel"
  #./lichtgehen <"$SPIELRASTER"
  #exit

chmod +x "$BOTA" "$BOTB"

#./lichtgehen <../freiesmagazin-2014-10-contest/results_turn1/Burow_Bock_cross.txt
#exit

if grep -q "USE_EIGENES_SPIEL *= *true" Makefile.modules; then
  echo "Eigenes Spiel"
  time ./lichtgehen <"$SPIELRASTER"
else
  echo "Serverspiel"
  # Spiel über den Server
  pushd ../freiesmagazin-2014-10-contest
  ./start.sh "$SPIELRASTER" "$BOTA" "$BOTB"
  #./start.sh "$SPIELRASTER" "$BOTA" "$BOTB" --log > bot.log 2>&1
  # gui/gui
  popd 
fi
