#!/bin/zsh

rm ./tronbot

export CXXFLAGS="-Wall -Werror -Wno-parentheses -std=c++14 -O2"

echo "Kompiliere tronbot…"
make -j1 || exit

echo "Starte tronbot…"
#<../Spielraster/simple.txt ./tronbot

BOTA="../src/tronbot"
#BOTA="bots/dummybot/bot"

#BOTB="../src/tronbot"
BOTB="bots/dummybot/bot"

#SPIELRASTER="../Spielraster/simple.txt"
#SPIELRASTER="../Spielraster/50x50.txt"
#SPIELRASTER="../Spielraster/5x5.txt"
SPIELRASTER="../Spielraster/10x10.txt"
#SPIELRASTER="../Spielraster/Ring.txt"
#SPIELRASTER="../Spielraster/Labyrinth.txt"
#SPIELRASTER="../Spielraster/Raumfüllen_1.txt"
#SPIELRASTER="../Spielraster/Raumfüllen_2.txt"

# nur ein Bot
#SPIELRASTER="../Spielraster/5x5_1.txt"

# Eigenes Spiel
time ./tronbot <"$SPIELRASTER"

exit

# Spiel über den Server
pushd ../freiesmagazin-2014-10-contest
#./start.sh "$SPIELRASTER" "$BOTA" "$BOTB"
 ./start.sh "$SPIELRASTER" "$BOTA" "$BOTB" --log > bot.log 2>&1
popd 
