# Graphische Ausgabe des Spielverlaufs
USE_UI_GTKMM = true

# Eingabe, nur mit USE_UI_GTKMM verwenden
# Muss für den Wettbewerb auf „false“ stehen
USE_EINGABE = false

# Spiel, ohne einen separaten Server.
# Muss für den Wettbewerb auf „false“ stehen
USE_EIGENES_SPIEL = true

# Mit Threads arbeiten (9 Stück)
USE_THREADS = true

# Zeitbeschränkung für die Tiefensuche (in Sekunden)
CPPFLAGS += -DZEITBESCHRAENKUNG=0.5
