CXX ?= g++
#CXXFLAGS ?= -Wall -Werror -Wno-parentheses -std=c++14 -O0 -ggdb
#CXXFLAGS ?= -Wall -Werror -Wno-parentheses -std=c++14 -O3
# für g++ Version < 4.9
CXXFLAGS ?= -Wall -Werror -Wno-parentheses -std=c++1y -O3

DEPGEN_FLAGS ?= -MMD -MP -MT $@ -MF $(@:.o=.d)
ifeq ($(USE_UI_GTKMM), true)
  CPPFLAGS += -DUSE_UI_GTKMM
endif
ifeq ($(USE_EINGABE), true)
  CPPFLAGS += -DUSE_EINGABE
endif
ifeq ($(USE_EIGENES_SPIEL), true)
  CPPFLAGS += -DUSE_EIGENES_SPIEL
endif
ifeq ($(USE_THREADS), true)
  CPPFLAGS += -DUSE_THREADS
endif

.PHONY: all

# Objekte kompilieren
.PHONY: objects
objects: $(OBJECTS)

%.o : %.cpp $(DEPTH)/Makefile.modules
	@echo $(CXX) -c $(SUBDIR)/$<
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(INCLUDE) $(DEPGEN_FLAGS) -o $@ -c $<

.PHONY: lib
lib: lib.a

lib.a: $(OBJECTS) $(DIRECTORIES)
	ld -o lib.a -r $(OBJECTS) $(DIRECTORIES:%=%/lib.a)

-include $(OBJECTS:%.o=%.d)

# make in den Unterverzeichnissen aufrufen
.PHONY: directories
directories: $(DIRECTORIES)

# make in den Unterverzeichnissen aufrufen
.PHONY : $(DIRECTORIES)
$(DIRECTORIES) :
	$(MAKE) -C $@

# Alle durch das Kompilieren erstellten Dateien entfernen
.PHONY : clean
clean :
	-$(RM) *.o
	-$(RM) *.d
	-$(RM) lib.a
ifeq ($(DEPTH),.)
	-$(RM) lichtgehen
	-$(RM) core core.*
	-$(RM) tags
endif
	-for d in $(DIRECTORIES); do $(MAKE) -C $$d $@; done
